---
# tasks file for patroni


- name: Add key postgres
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add repo postgres
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main
    state: present
    update_cache: yes

- name: install "{{pt_psql_pg}}" 
  apt:
    name: "{{pt_psql_pg}}"
    state: present
  tags: pg_vers

- name: disable postgres
  service:
    name: postgresql
    state: stopped
    enabled: no
  tags: pg_stop

- name: install packages
  apt:
    pkg: "{{pt_packages}}"
    state: present

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
    

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ pt_pip_packages }}"

- name: unit for systemd 
  copy:
    src: patroni.service
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'
  tags: systemd

- name: create dir
  file:
    path: /data/
    recurse: yes
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
  tags: pt_data

- name: create dir
  file:
    path: /data/patroni
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: 0750
  tags: pt_dir

- name: move config patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
  tags: conf

- name: move condig pgbouncer
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
  tags: pgconf

- name: move access users
  template:
    src: userlist.txt.j2
    dest: /etc/pgbouncer/userlist.txt
  tags: pguser

- name: start pgbouncer
  service:
    name: pgbouncer
    state: restarted
    enabled: yes
  tags: pgstart 

- name: start patroni
  service:
    name: patroni
    state: restarted
    enabled: yes
  tags: start

- name: install vip-ip
  apt:
    name: vip-manager
    state: present
  tags: vip

- name: move vip-unit
  template:
    src: vip-manager.service.j2
    dest: /lib/systemd/system/vip-manager.service
  tags: vip-unit

- name: move vip-conf
  template:
    src: vip-manager.yml.j2
    dest: /etc/default/vip-manager.yml
  tags: vip-conf

- name:
  command: systemctl daemon-reload

- name: start vip
  service:
    name: vip-manager
    state: restarted
    enabled: yes
  tags: vip-rest

