---
# tasks file for patroni

- name: Add key postgres
  apt_key:
    url: https://www.postgresql.org/media/keys/ACCC4CF8.asc
    state: present

- name: add repo postgres
  apt_repository:
    repo: deb http://apt.postgresql.org/pub/repos/apt buster-pgdg main
    state: present
    update_cache: yes

- name: install "{{pt_pg_vers}}" 
  apt:
    name: "{{pt_pg_vers}}"
    state: present
  tags: pg_vers

- name: stop postgresql
  service:
    name: postgresql 
    state: stopped
    enabled: no

- name: install packages
  apt:
    pkg: "{{pt_packages}}"
    state: present

- name: Install and upgrade pip
  pip:
    name: pip
    extra_args: --upgrade
    executable: pip3
    

- name: Install pip packages for patroni
  pip:
    name: "{{ item.name }}"
    state: "{{ item.state }}"
    executable: "{{ item.executable }}"
  with_items:
    - "{{ pt_pip_packages }}"

- name: unit for systemd 
  copy:
    src: patroni.service
    dest: /etc/systemd/system/patroni.service
    owner: root
    group: root
    mode: '0644'
  tags: systemd

- name: create dir
  file:
    path: /data/
    recurse: yes
    state: directory
    owner: postgres
    group: postgres
    mode: 0750
  tags: pt_data

- name: create dir
  file:
    path: /data/patroni
    state: directory
    recurse: yes
    owner: postgres
    group: postgres
    mode: 0750
  tags: pt_dir

- name: copy ath.py
  copy:
    src: ath.py
    dest: /usr/bin/ath.py
    owner: root
    group: root
    mode: uo+x

- name: move config pgbouncer
  template:
    src: pgbouncer.ini.j2
    dest: /etc/pgbouncer/pgbouncer.ini
  tags: pgconf
  notify:
     - restart pgbouncer
  tags: suka

- name: install vip-ip
  apt:
    name: vip-manager
    state: present
  tags: vip

- name: move vip-unit
  copy:
    src: vip-manager.service
    dest: /lib/systemd/system/vip-manager.service
    owner: root
    group: root
    mode: '0644'
  tags: vip-unit
  notify:
     - daemon reload

- name: move vip-conf
  template:
    src: vip-manager.yml.j2
    dest: /etc/default/vip-manager.yml
  tags: vip-conf
  notify:
      - vip start

- name: move config patroni
  template:
    src: patroni.yml.j2
    dest: /etc/patroni.yml
  notify: 
     - restart patroni
  tags: conf

- name: crontab
  cron:
    name: pass for pg
    minute: "*/5"
    job: '/usr/bin/ath.py /etc/pgbouncer/userlist.txt "dbname=template1 user=postgres" && chown postgres:postgres /etc/pgbouncer/userlist.txt'
    user: root
