---
# handlers file for patroni

#- name: disable postgres
#  service:
#     name: postgresql
#     state: stopped
#     enabled: no

- name: restart pgbouncer
  service:
     name: pgbouncer
     state: restarted
     enabled: yes

- name: restart patroni
  service:
     name: patroni
     state: restarted
     enabled: yes

- name: daemon reload
  command: systemctl daemon-reload

- name: vip start
  service:
     name: vip-manager
     state: started
     enabled: yes
